site_name: Agent Bench Project
theme:
  name: material
  palette:
    scheme: default
    primary: blue grey
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: resources/logo.jpg

use_directory_urls: false
docs_dir: docs

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Evaluators: evaluators.md
  - Evaluate with Evaluation Dataset: graph_evaluator_class.md
  - Evaluate with Conversational Setup: evaluation_with_conversational_setup.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - sane_lists
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - tags

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false